"use client";

import { useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  HelpCircle,
  ListChecks,
  Pencil,
  Plus,
  Sparkles,
  Timer,
  Trash2,
  X,
} from "lucide-react";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { SkillLinker } from "@/components/skill-linker";
import { AIGuideModal } from "@/components/ai-guide-modal";
import { EntityExportButton } from "@/components/entity-io-controls";
import { DeadlineEditor } from "@/components/deadline-editor";
import { startFocus } from "@/components/focus-timer";
import { ProgressRing } from "@/components/progress-ring";

type AIProvenance = {
  source: "ai_guide";
  model: string;
  durationMs: number;
  generatedAt: string;
};

function isAIProvenance(m: unknown): m is AIProvenance {
  return (
    typeof m === "object" &&
    m !== null &&
    (m as { source?: string }).source === "ai_guide"
  );
}

function AIBadge({ metadata }: { metadata: unknown }) {
  if (!isAIProvenance(metadata)) return null;
  const secs = (metadata.durationMs / 1000).toFixed(1);
  return (
    <span
      className="inline-flex items-center gap-0.5 rounded-full border border-trails-accent/50 bg-trails-accent/15 px-1.5 py-0.5 text-[9px] font-medium text-trails-accent"
      title={`Generated by ${metadata.model} (${secs}s) — ${new Date(metadata.generatedAt).toLocaleString()}`}
    >
      <Sparkles className="h-2 w-2" />
      AI
    </span>
  );
}

const epicStatusClass: Record<string, string> = {
  not_started: "text-trails-fg-dim",
  in_progress: "text-trails-info",
  completed: "text-trails-good",
  paused: "text-trails-warn",
  abandoned: "text-trails-bad",
};

export default function EpicDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const utils = trpc.useUtils();

  const { data: epic, isLoading, error } = trpc.epic.byId.useQuery({ id });
  const { data: allSkills } = trpc.skill.list.useQuery();

  const invalidate = () => {
    utils.epic.byId.invalidate({ id });
    utils.tree.get.invalidate();
    utils.skill.list.invalidate();
  };

  const createMilestone = trpc.milestone.create.useMutation({
    onSuccess: () => {
      invalidate();
      setNewTitle("");
    },
  });
  const updateMilestone = trpc.milestone.update.useMutation({
    onSuccess: () => {
      invalidate();
      setEditingId(null);
    },
  });
  const toggleMilestone = trpc.milestone.toggleComplete.useMutation({
    onSuccess: invalidate,
  });
  const deleteMilestone = trpc.milestone.delete.useMutation({
    onSuccess: invalidate,
  });
  const linkSkill = trpc.milestone.linkSkill.useMutation({
    onSuccess: invalidate,
  });
  const unlinkSkill = trpc.milestone.unlinkSkill.useMutation({
    onSuccess: invalidate,
  });
  const updateEpic = trpc.epic.update.useMutation({ onSuccess: invalidate });
  const createStep = trpc.step.create.useMutation({ onSuccess: invalidate });
  const updateStep = trpc.step.update.useMutation({ onSuccess: invalidate });
  const toggleStep = trpc.step.toggleComplete.useMutation({
    onSuccess: invalidate,
  });
  const deleteStep = trpc.step.delete.useMutation({ onSuccess: invalidate });

  // Which milestones have their steps panel expanded.
  const [expandedSteps, setExpandedSteps] = useState<Set<string>>(new Set());
  const toggleStepsPanel = (mid: string) =>
    setExpandedSteps((prev) => {
      const next = new Set(prev);
      if (next.has(mid)) next.delete(mid);
      else next.add(mid);
      return next;
    });

  const [newTitle, setNewTitle] = useState("");
  const [newTier, setNewTier] = useState(0);
  const [newStartDate, setNewStartDate] = useState("");
  const [newDate, setNewDate] = useState("");

  const [editingId, setEditingId] = useState<string | null>(null);
  const [editTitle, setEditTitle] = useState("");
  const [editDate, setEditDate] = useState("");
  const [showGuide, setShowGuide] = useState(false);

  function startEdit(m: { id: string; title: string; estimatedAchievementDate: string | null }) {
    setEditingId(m.id);
    setEditTitle(m.title);
    setEditDate(m.estimatedAchievementDate ?? "");
  }

  function saveEdit() {
    if (!editingId || !editTitle.trim()) return;
    updateMilestone.mutate({
      id: editingId,
      title: editTitle.trim(),
      estimatedAchievementDate: editDate || null,
    });
  }

  if (isLoading)
    return <p className="text-sm text-trails-fg-dim">Loading...</p>;
  if (error || !epic)
    return (
      <div className="rounded-md border border-trails-bad/60 bg-trails-bad/10 p-4">
        <p className="text-sm text-trails-bad">Epic not found.</p>
        <Link
          href="/epics"
          className="mt-3 inline-block text-sm text-trails-accent underline"
        >
          ← Back to epics
        </Link>
      </div>
    );

  const byTier = new Map<number, typeof epic.milestones>();
  for (const m of [...epic.milestones].sort(
    (a, b) => a.tier - b.tier || a.position - b.position,
  )) {
    const arr = byTier.get(m.tier) ?? [];
    arr.push(m);
    byTier.set(m.tier, arr);
  }
  const tiers = Array.from(byTier.keys()).sort((a, b) => a - b);

  return (
    <div className="space-y-8">
      <header>
        <Link
          href="/epics"
          className="inline-flex items-center gap-1 text-xs text-trails-fg-dim hover:text-trails-accent"
        >
          <ChevronLeft className="h-3 w-3" /> All epics
        </Link>
        <div className="mt-2 flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h1 className="flex items-center gap-2">
              {epic.category && (
                <span
                  className="h-3 w-3 shrink-0 rounded-full ring-2 ring-trails-trim/30"
                  style={{ backgroundColor: epic.category.color }}
                  title={epic.category.name}
                />
              )}
              <span className="truncate">{epic.title}</span>
            </h1>
            {epic.description && (
              <p className="mt-1 text-sm text-trails-fg-dim">
                {epic.description}
              </p>
            )}
            <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-[11px] text-trails-fg-dim">
              {epic.category && <span>{epic.category.name}</span>}
              <span
                className={
                  "font-display uppercase tracking-widest " +
                  (epicStatusClass[epic.status] ?? "text-trails-fg-dim")
                }
              >
                {epic.status.replace("_", " ")}
              </span>
              <DeadlineEditor
                value={epic.targetDate}
                onSave={(d) => updateEpic.mutate({ id, targetDate: d })}
                saving={updateEpic.isPending}
                idleLabel="Deadline"
              />
            </div>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            <EntityExportButton epicId={id} />
            <button
              type="button"
              onClick={() => setShowGuide(true)}
              className="inline-flex items-center gap-1.5 rounded-md border-2 border-trails-accent bg-trails-accent/15 px-3 py-1.5 font-display text-xs uppercase tracking-widest text-trails-accent-bright hover:bg-trails-accent/25"
              title="Ask the AI Guide (local Ollama) to propose new Milestones extending this Epic. The Guide reads existing milestones, target date, and category context."
            >
              <Sparkles className="h-3.5 w-3.5" />
              Ask the Guide
            </button>
          </div>
        </div>
      </header>

      <AIGuideModal
        epicId={id}
        open={showGuide}
        onClose={() => setShowGuide(false)}
      />

      <section>
        <h2 className="!m-0 !border-0 !p-0 mb-3 flex items-center gap-2 font-display text-sm uppercase tracking-widest text-trails-accent">
          Milestones · {epic.milestones.length}
          <span
            title="Each milestone has a tier (same tier = parallel work) + an optional target date. Click the circle to mark complete. Edit pencil tweaks title + date inline. Arrows shift the tier up/down."
            className="text-trails-info"
          >
            <HelpCircle className="h-3.5 w-3.5" />
          </span>
        </h2>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            if (!newTitle.trim()) return;
            createMilestone.mutate({
              epicId: id,
              title: newTitle.trim(),
              tier: newTier,
              estimatedStartDate: newStartDate || undefined,
              estimatedAchievementDate: newDate || undefined,
            });
            setNewStartDate("");
            setNewDate("");
          }}
          className="mb-6 grid grid-cols-1 gap-2 rounded-lg border border-zinc-200 bg-white p-3 sm:grid-cols-[1fr_110px_150px_150px_auto] dark:border-zinc-800 dark:bg-zinc-900"
        >
          <input
            type="text"
            placeholder="New milestone (e.g. Pass N5 Level)"
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            className="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"
          />
          <label className="flex items-center gap-2 rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950">
            <span className="text-xs text-zinc-500">Tier</span>
            <input
              type="number"
              min={0}
              max={50}
              value={newTier}
              onChange={(e) =>
                setNewTier(Math.max(0, Number(e.target.value) || 0))
              }
              className="w-full bg-transparent text-sm focus:outline-none"
            />
          </label>
          <input
            type="date"
            value={newStartDate}
            onChange={(e) => setNewStartDate(e.target.value)}
            title="Estimated start date (optional)"
            aria-label="Estimated start date"
            className="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"
          />
          <input
            type="date"
            value={newDate}
            onChange={(e) => setNewDate(e.target.value)}
            title="Estimated achievement date (optional)"
            aria-label="Estimated achievement date"
            className="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"
          />
          <button
            type="submit"
            disabled={createMilestone.isPending || !newTitle.trim()}
            className="rounded-md bg-zinc-900 px-3 py-2 text-sm font-medium text-white hover:bg-zinc-700 disabled:opacity-50 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-200"
          >
            Add
          </button>
        </form>

        {tiers.length === 0 ? (
          <p className="text-sm text-zinc-500">No milestones yet.</p>
        ) : (
          <div className="space-y-4">
            {tiers.map((tier) => (
              <div key={tier}>
                <div className="mb-2 flex items-center gap-2">
                  <span className="font-display text-[10px] uppercase tracking-widest text-trails-accent">
                    Tier {tier}
                  </span>
                  {(byTier.get(tier)?.length ?? 0) > 1 && (
                    <span
                      title="Multiple milestones at this tier are intended to be tackled in parallel."
                      className="rounded-full border border-trails-trim/40 bg-trails-bg-deep/60 px-2 py-0.5 font-display text-[10px] uppercase tracking-wider text-trails-info"
                    >
                      ⇉ parallel
                    </span>
                  )}
                </div>
                <ul className="divide-y divide-trails-trim/20 rounded-lg border">
                  {byTier.get(tier)!.map((m) => {
                    const isEditing = editingId === m.id;
                    const linked = m.skills.map((ms) => ({
                      id: ms.skill.id,
                      name: ms.skill.name,
                    }));
                    return (
                      <li
                        key={m.id}
                        className="flex flex-col gap-2 px-4 py-3"
                      >
                        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                        <div className="flex min-w-0 flex-1 flex-col gap-1.5">
                          {isEditing ? (
                            <div className="flex flex-wrap items-center gap-2">
                              <input
                                type="text"
                                value={editTitle}
                                onChange={(e) =>
                                  setEditTitle(e.target.value)
                                }
                                onKeyDown={(e) => {
                                  if (e.key === "Enter") saveEdit();
                                  if (e.key === "Escape") setEditingId(null);
                                }}
                                autoFocus
                                className="flex-1 min-w-[200px] rounded-md border border-zinc-300 bg-white px-2 py-1 text-sm dark:border-zinc-700 dark:bg-zinc-950"
                              />
                              <input
                                type="date"
                                value={editDate}
                                onChange={(e) => setEditDate(e.target.value)}
                                className="rounded-md border border-zinc-300 bg-white px-2 py-1 text-sm dark:border-zinc-700 dark:bg-zinc-950"
                              />
                              <button
                                type="button"
                                title="Save"
                                disabled={
                                  !editTitle.trim() ||
                                  updateMilestone.isPending
                                }
                                onClick={saveEdit}
                                className="rounded-md bg-zinc-900 p-1.5 text-white hover:bg-zinc-700 disabled:opacity-50 dark:bg-zinc-50 dark:text-zinc-900"
                              >
                                <Check className="h-3.5 w-3.5" />
                              </button>
                              <button
                                type="button"
                                title="Cancel"
                                onClick={() => setEditingId(null)}
                                className="rounded-md border border-zinc-200 p-1.5 hover:bg-zinc-100 dark:border-zinc-800 dark:hover:bg-zinc-800"
                              >
                                <X className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          ) : (
                            <button
                              type="button"
                              onClick={() =>
                                toggleMilestone.mutate({ id: m.id })
                              }
                              title={
                                m.status === "completed"
                                  ? `Click to mark "${m.title}" not complete`
                                  : `Click to mark "${m.title}" complete (grants XP to linked Skills)`
                              }
                              className="flex w-full items-center gap-3 rounded-md px-1 py-0.5 text-left transition-colors hover:bg-trails-bg-glow/40"
                            >
                              {m.status === "completed" ? (
                                <CheckCircle2 className="h-4 w-4 shrink-0 text-trails-good" />
                              ) : (
                                <Circle className="h-4 w-4 shrink-0 text-trails-fg-dim" />
                              )}
                              <span
                                className={
                                  m.status === "completed"
                                    ? "text-sm text-trails-fg-dim line-through"
                                    : "text-sm font-medium text-trails-fg"
                                }
                              >
                                {m.title}
                              </span>
                              <AIBadge metadata={m.metadata} />
                              {m.steps.length > 0 && (
                                <span
                                  className="inline-flex items-center gap-1"
                                  title={`${m.steps.filter((s) => s.isCompleted).length} of ${m.steps.length} steps complete`}
                                >
                                  <ProgressRing
                                    value={
                                      m.steps.filter((s) => s.isCompleted).length /
                                      m.steps.length
                                    }
                                  />
                                  <span className="font-mono text-[10px] text-trails-fg-dim">
                                    {m.steps.filter((s) => s.isCompleted).length}/
                                    {m.steps.length} steps
                                  </span>
                                </span>
                              )}
                            </button>
                          )}
                          {!isEditing && (
                            <div className="ml-7 flex flex-wrap items-center gap-x-3 gap-y-1.5">
                              <DeadlineEditor
                                value={m.estimatedStartDate}
                                onSave={(d) =>
                                  updateMilestone.mutate({
                                    id: m.id,
                                    estimatedStartDate: d,
                                  })
                                }
                                saving={
                                  updateMilestone.isPending &&
                                  updateMilestone.variables?.id === m.id &&
                                  "estimatedStartDate" in
                                    (updateMilestone.variables ?? {})
                                }
                                idleLabel="Start"
                              />
                              <DeadlineEditor
                                value={m.estimatedAchievementDate}
                                onSave={(d) =>
                                  updateMilestone.mutate({
                                    id: m.id,
                                    estimatedAchievementDate: d,
                                  })
                                }
                                saving={
                                  updateMilestone.isPending &&
                                  updateMilestone.variables?.id === m.id &&
                                  "estimatedAchievementDate" in
                                    (updateMilestone.variables ?? {})
                                }
                                idleLabel="Deadline"
                              />
                              <SkillLinker
                                linked={linked}
                                available={allSkills?.map((s) => ({
                                  id: s.id,
                                  name: s.name,
                                  level: s.level,
                                }))}
                                onLink={(skillId) =>
                                  linkSkill.mutate({
                                    milestoneId: m.id,
                                    skillId,
                                  })
                                }
                                onUnlink={(skillId) =>
                                  unlinkSkill.mutate({
                                    milestoneId: m.id,
                                    skillId,
                                  })
                                }
                              />
                            </div>
                          )}
                        </div>
                        {!isEditing && (
                          <div className="flex shrink-0 items-center gap-1 self-start sm:self-auto">
                            <button
                              type="button"
                              title={
                                expandedSteps.has(m.id)
                                  ? "Hide steps"
                                  : "Show / add / edit steps (each can have its own deadline)"
                              }
                              onClick={() => toggleStepsPanel(m.id)}
                              className={cn(
                                "inline-flex items-center gap-1 rounded-md border p-1 text-zinc-500 hover:bg-zinc-100 dark:border-zinc-800 dark:hover:bg-zinc-800",
                                expandedSteps.has(m.id)
                                  ? "border-trails-accent/50 text-trails-accent"
                                  : "border-zinc-200",
                              )}
                            >
                              <ListChecks className="h-3.5 w-3.5" />
                              {m.steps.length > 0 && (
                                <span className="font-mono text-[10px]">
                                  {m.steps.filter((s) => s.isCompleted).length}/
                                  {m.steps.length}
                                </span>
                              )}
                              <ChevronDown
                                className={cn(
                                  "h-3 w-3 transition-transform",
                                  expandedSteps.has(m.id) && "rotate-180",
                                )}
                              />
                            </button>
                            <button
                              type="button"
                              title="Edit title + date"
                              onClick={() => startEdit(m)}
                              className="rounded-md border border-zinc-200 p-1 text-zinc-500 hover:bg-zinc-100 dark:border-zinc-800 dark:hover:bg-zinc-800"
                            >
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                            <button
                              type="button"
                              title="Move down a tier"
                              disabled={
                                m.tier === 0 || updateMilestone.isPending
                              }
                              onClick={() =>
                                updateMilestone.mutate({
                                  id: m.id,
                                  tier: m.tier - 1,
                                })
                              }
                              className="rounded-md border border-zinc-200 p-1 text-zinc-500 hover:bg-zinc-100 disabled:opacity-30 dark:border-zinc-800 dark:hover:bg-zinc-800"
                            >
                              <ChevronLeft className="h-3.5 w-3.5" />
                            </button>
                            <button
                              type="button"
                              title="Move up a tier"
                              disabled={updateMilestone.isPending}
                              onClick={() =>
                                updateMilestone.mutate({
                                  id: m.id,
                                  tier: m.tier + 1,
                                })
                              }
                              className="rounded-md border border-zinc-200 p-1 text-zinc-500 hover:bg-zinc-100 disabled:opacity-30 dark:border-zinc-800 dark:hover:bg-zinc-800"
                            >
                              <ChevronRight className="h-3.5 w-3.5" />
                            </button>
                            <button
                              type="button"
                              onClick={() => {
                                if (
                                  confirm(
                                    `Delete "${m.title}"? Its steps, resources, and prerequisites will be removed too.`,
                                  )
                                ) {
                                  deleteMilestone.mutate({ id: m.id });
                                }
                              }}
                              title="Delete this milestone (and its steps/resources/prereqs)"
                              className="ml-2 rounded-md border p-1 text-trails-fg-dim hover:bg-trails-bg-glow hover:text-trails-bad"
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        )}
                        </div>
                        {expandedSteps.has(m.id) && (
                          <MilestoneSteps
                            steps={m.steps}
                            skillId={m.skills[0]?.skill.id ?? null}
                            onAdd={(title) =>
                              createStep.mutate({ milestoneId: m.id, title })
                            }
                            onToggle={(stepId) =>
                              toggleStep.mutate({ id: stepId })
                            }
                            onRename={(stepId, title) =>
                              updateStep.mutate({ id: stepId, title })
                            }
                            onSetDue={(stepId, dueDate) =>
                              updateStep.mutate({ id: stepId, dueDate })
                            }
                            onDelete={(stepId) =>
                              deleteStep.mutate({ id: stepId })
                            }
                            addPending={createStep.isPending}
                            savingStepId={
                              updateStep.isPending
                                ? (updateStep.variables?.id ?? null)
                                : null
                            }
                          />
                        )}
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

type StepData = {
  id: string;
  title: string;
  isCompleted: boolean;
  dueDate: string | null;
};

/**
 * Expandable per-milestone steps editor. Each step can be toggled complete,
 * renamed inline, given/cleared its own deadline (DeadlineEditor), or deleted.
 * A small form at the bottom adds new steps. Saves go straight to the step
 * router via the handlers the parent supplies.
 */
function MilestoneSteps({
  steps,
  skillId,
  onAdd,
  onToggle,
  onRename,
  onSetDue,
  onDelete,
  addPending,
  savingStepId,
}: {
  steps: StepData[];
  skillId: string | null;
  onAdd: (title: string) => void;
  onToggle: (stepId: string) => void;
  onRename: (stepId: string, title: string) => void;
  onSetDue: (stepId: string, dueDate: string | null) => void;
  onDelete: (stepId: string) => void;
  addPending: boolean;
  savingStepId: string | null;
}) {
  const [newStep, setNewStep] = useState("");
  const [editingStep, setEditingStep] = useState<string | null>(null);
  const [editText, setEditText] = useState("");
  const ordered = [...steps].sort((a, b) => a.title.localeCompare(b.title));

  return (
    <div className="ml-7 rounded-md border border-trails-trim/30 bg-trails-bg-deep/40 p-2">
      {ordered.length === 0 ? (
        <p className="px-1 py-1 text-[11px] italic text-trails-fg-dim">
          No steps yet — break this milestone into concrete steps below. Each
          step can have its own deadline.
        </p>
      ) : (
        <ul className="space-y-1">
          {ordered.map((s) => (
            <li key={s.id} className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => onToggle(s.id)}
                title={s.isCompleted ? "Mark not done" : "Mark done"}
                className="shrink-0"
              >
                {s.isCompleted ? (
                  <CheckCircle2 className="h-3.5 w-3.5 text-trails-good" />
                ) : (
                  <Circle className="h-3.5 w-3.5 text-trails-fg-dim" />
                )}
              </button>
              {editingStep === s.id ? (
                <input
                  type="text"
                  value={editText}
                  autoFocus
                  onChange={(e) => setEditText(e.target.value)}
                  onBlur={() => {
                    const v = editText.trim();
                    if (v && v !== s.title) onRename(s.id, v);
                    setEditingStep(null);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter")
                      (e.target as HTMLInputElement).blur();
                    if (e.key === "Escape") setEditingStep(null);
                  }}
                  className="min-w-0 flex-1 rounded-md border border-trails-accent/50 bg-trails-bg-deep/70 px-1.5 py-0.5 text-xs text-trails-fg focus:outline-none"
                />
              ) : (
                <button
                  type="button"
                  onClick={() => {
                    setEditingStep(s.id);
                    setEditText(s.title);
                  }}
                  title="Click to rename"
                  className={cn(
                    "min-w-0 flex-1 truncate text-left text-xs",
                    s.isCompleted
                      ? "text-trails-fg-dim line-through"
                      : "text-trails-fg",
                  )}
                >
                  {s.title}
                </button>
              )}
              <DeadlineEditor
                value={s.dueDate}
                onSave={(d) => onSetDue(s.id, d)}
                saving={savingStepId === s.id}
                idleLabel="Due"
                tone="muted"
              />
              {!s.isCompleted && (
                <button
                  type="button"
                  onClick={() =>
                    startFocus({
                      label: s.title,
                      refType: "step",
                      refId: s.id,
                      skillId,
                    })
                  }
                  title="Start a focus session on this step"
                  className="shrink-0 rounded p-0.5 text-trails-fg-dim hover:text-jrpg-gold"
                >
                  <Timer className="h-3 w-3" />
                </button>
              )}
              <button
                type="button"
                onClick={() => onDelete(s.id)}
                title="Delete step"
                className="shrink-0 rounded p-0.5 text-trails-fg-dim hover:text-trails-bad"
              >
                <X className="h-3 w-3" />
              </button>
            </li>
          ))}
        </ul>
      )}
      <form
        onSubmit={(e) => {
          e.preventDefault();
          const v = newStep.trim();
          if (!v) return;
          onAdd(v);
          setNewStep("");
        }}
        className="mt-2 flex items-center gap-1"
      >
        <Plus className="h-3 w-3 text-trails-fg-dim" />
        <input
          type="text"
          value={newStep}
          onChange={(e) => setNewStep(e.target.value)}
          placeholder="Add a step…"
          className="min-w-0 flex-1 rounded-md border border-trails-trim/40 bg-trails-bg-deep/60 px-2 py-1 text-xs text-trails-fg focus:outline-none focus:ring-1 focus:ring-trails-accent/40"
        />
        <button
          type="submit"
          disabled={addPending || !newStep.trim()}
          className="rounded-md border border-trails-accent/50 bg-trails-accent/10 px-2 py-1 font-display text-[10px] uppercase tracking-widest text-trails-accent hover:bg-trails-accent/20 disabled:opacity-40"
        >
          Add
        </button>
      </form>
    </div>
  );
}
